//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Database1Model", "FK_cliente_pago", "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gimnasio.clientes), "Pagos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gimnasio.Pagos), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "fk_tipoCuota_pago", "Cuotas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gimnasio.Cuotas), "Pagos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gimnasio.Pagos), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "fk_cliente_factura", "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gimnasio.clientes), "Facturas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gimnasio.Facturas), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "fk_pago_factura", "Pagos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gimnasio.Pagos), "Facturas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gimnasio.Facturas), true)]

#endregion

namespace Gimnasio
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Database1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Database1Entities object using the connection string found in the 'Database1Entities' section of the application configuration file.
        /// </summary>
        public Database1Entities() : base("name=Database1Entities", "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(string connectionString) : base(connectionString, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(EntityConnection connection) : base(connection, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<clientes> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<clientes>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<clientes> _clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cuotas> Cuotas
        {
            get
            {
                if ((_Cuotas == null))
                {
                    _Cuotas = base.CreateObjectSet<Cuotas>("Cuotas");
                }
                return _Cuotas;
            }
        }
        private ObjectSet<Cuotas> _Cuotas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pagos> Pagos
        {
            get
            {
                if ((_Pagos == null))
                {
                    _Pagos = base.CreateObjectSet<Pagos>("Pagos");
                }
                return _Pagos;
            }
        }
        private ObjectSet<Pagos> _Pagos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Facturas> Facturas
        {
            get
            {
                if ((_Facturas == null))
                {
                    _Facturas = base.CreateObjectSet<Facturas>("Facturas");
                }
                return _Facturas;
            }
        }
        private ObjectSet<Facturas> _Facturas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclientes(clientes clientes)
        {
            base.AddObject("clientes", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cuotas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCuotas(Cuotas cuotas)
        {
            base.AddObject("Cuotas", cuotas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pagos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagos(Pagos pagos)
        {
            base.AddObject("Pagos", pagos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Facturas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacturas(Facturas facturas)
        {
            base.AddObject("Facturas", facturas);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new clientes object.
        /// </summary>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        public static clientes Createclientes(global::System.Int32 idCliente)
        {
            clientes clientes = new clientes();
            clientes.idCliente = idCliente;
            return clientes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                if (_idCliente != value)
                {
                    OnidClienteChanging(value);
                    ReportPropertyChanging("idCliente");
                    _idCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCliente");
                    OnidClienteChanged();
                }
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_nacimiento
        {
            get
            {
                return _fecha_nacimiento;
            }
            set
            {
                Onfecha_nacimientoChanging(value);
                ReportPropertyChanging("fecha_nacimiento");
                _fecha_nacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_nacimiento");
                Onfecha_nacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_nacimiento;
        partial void Onfecha_nacimientoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_nacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ingreso
        {
            get
            {
                return _fecha_ingreso;
            }
            set
            {
                Onfecha_ingresoChanging(value);
                ReportPropertyChanging("fecha_ingreso");
                _fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ingreso");
                Onfecha_ingresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ingreso;
        partial void Onfecha_ingresoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ingresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> altura
        {
            get
            {
                return _altura;
            }
            set
            {
                OnalturaChanging(value);
                ReportPropertyChanging("altura");
                _altura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("altura");
                OnalturaChanged();
            }
        }
        private Nullable<global::System.Int32> _altura;
        partial void OnalturaChanging(Nullable<global::System.Int32> value);
        partial void OnalturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private Nullable<global::System.Int32> _peso;
        partial void OnpesoChanging(Nullable<global::System.Int32> value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nro_cedula
        {
            get
            {
                return _nro_cedula;
            }
            set
            {
                Onnro_cedulaChanging(value);
                ReportPropertyChanging("nro_cedula");
                _nro_cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nro_cedula");
                Onnro_cedulaChanged();
            }
        }
        private global::System.String _nro_cedula;
        partial void Onnro_cedulaChanging(global::System.String value);
        partial void Onnro_cedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasfoto
        {
            get
            {
                return _hasfoto;
            }
            set
            {
                OnhasfotoChanging(value);
                ReportPropertyChanging("hasfoto");
                _hasfoto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasfoto");
                OnhasfotoChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasfoto;
        partial void OnhasfotoChanging(Nullable<global::System.Boolean> value);
        partial void OnhasfotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_cliente_pago", "Pagos")]
        public EntityCollection<Pagos> Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pagos>("Database1Model.FK_cliente_pago", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pagos>("Database1Model.FK_cliente_pago", "Pagos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_cliente_factura", "Facturas")]
        public EntityCollection<Facturas> Facturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Facturas>("Database1Model.fk_cliente_factura", "Facturas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Facturas>("Database1Model.fk_cliente_factura", "Facturas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Cuotas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cuotas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cuotas object.
        /// </summary>
        /// <param name="idCuota">Initial value of the idCuota property.</param>
        public static Cuotas CreateCuotas(global::System.Int32 idCuota)
        {
            Cuotas cuotas = new Cuotas();
            cuotas.idCuota = idCuota;
            return cuotas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCuota
        {
            get
            {
                return _idCuota;
            }
            set
            {
                if (_idCuota != value)
                {
                    OnidCuotaChanging(value);
                    ReportPropertyChanging("idCuota");
                    _idCuota = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCuota");
                    OnidCuotaChanged();
                }
            }
        }
        private global::System.Int32 _idCuota;
        partial void OnidCuotaChanging(global::System.Int32 value);
        partial void OnidCuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monto
        {
            get
            {
                return _monto;
            }
            set
            {
                OnmontoChanging(value);
                ReportPropertyChanging("monto");
                _monto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monto");
                OnmontoChanged();
            }
        }
        private global::System.String _monto;
        partial void OnmontoChanging(global::System.String value);
        partial void OnmontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> diasHabilitados
        {
            get
            {
                return _diasHabilitados;
            }
            set
            {
                OndiasHabilitadosChanging(value);
                ReportPropertyChanging("diasHabilitados");
                _diasHabilitados = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("diasHabilitados");
                OndiasHabilitadosChanged();
            }
        }
        private Nullable<global::System.Int32> _diasHabilitados;
        partial void OndiasHabilitadosChanging(Nullable<global::System.Int32> value);
        partial void OndiasHabilitadosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_tipoCuota_pago", "Pagos")]
        public EntityCollection<Pagos> Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pagos>("Database1Model.fk_tipoCuota_pago", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pagos>("Database1Model.fk_tipoCuota_pago", "Pagos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Facturas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Facturas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Facturas object.
        /// </summary>
        /// <param name="idFactura">Initial value of the idFactura property.</param>
        /// <param name="fk_pago">Initial value of the fk_pago property.</param>
        public static Facturas CreateFacturas(global::System.Int32 idFactura, global::System.Int64 fk_pago)
        {
            Facturas facturas = new Facturas();
            facturas.idFactura = idFactura;
            facturas.fk_pago = fk_pago;
            return facturas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFactura
        {
            get
            {
                return _idFactura;
            }
            set
            {
                if (_idFactura != value)
                {
                    OnidFacturaChanging(value);
                    ReportPropertyChanging("idFactura");
                    _idFactura = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idFactura");
                    OnidFacturaChanged();
                }
            }
        }
        private global::System.Int32 _idFactura;
        partial void OnidFacturaChanging(global::System.Int32 value);
        partial void OnidFacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_pago
        {
            get
            {
                return _fk_pago;
            }
            set
            {
                Onfk_pagoChanging(value);
                ReportPropertyChanging("fk_pago");
                _fk_pago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_pago");
                Onfk_pagoChanged();
            }
        }
        private global::System.Int64 _fk_pago;
        partial void Onfk_pagoChanging(global::System.Int64 value);
        partial void Onfk_pagoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fk_cliente
        {
            get
            {
                return _fk_cliente;
            }
            set
            {
                Onfk_clienteChanging(value);
                ReportPropertyChanging("fk_cliente");
                _fk_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_cliente");
                Onfk_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _fk_cliente;
        partial void Onfk_clienteChanging(Nullable<global::System.Int32> value);
        partial void Onfk_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nro_Factura
        {
            get
            {
                return _Nro_Factura;
            }
            set
            {
                OnNro_FacturaChanging(value);
                ReportPropertyChanging("Nro_Factura");
                _Nro_Factura = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nro_Factura");
                OnNro_FacturaChanged();
            }
        }
        private global::System.String _Nro_Factura;
        partial void OnNro_FacturaChanging(global::System.String value);
        partial void OnNro_FacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_Emision
        {
            get
            {
                return _Fecha_Emision;
            }
            set
            {
                OnFecha_EmisionChanging(value);
                ReportPropertyChanging("Fecha_Emision");
                _Fecha_Emision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Emision");
                OnFecha_EmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_Emision;
        partial void OnFecha_EmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_EmisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Pagador
        {
            get
            {
                return _Nombre_Pagador;
            }
            set
            {
                OnNombre_PagadorChanging(value);
                ReportPropertyChanging("Nombre_Pagador");
                _Nombre_Pagador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre_Pagador");
                OnNombre_PagadorChanged();
            }
        }
        private global::System.String _Nombre_Pagador;
        partial void OnNombre_PagadorChanging(global::System.String value);
        partial void OnNombre_PagadorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_cliente_factura", "clientes")]
        public clientes clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.fk_cliente_factura", "clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.fk_cliente_factura", "clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clientes> clientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.fk_cliente_factura", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clientes>("Database1Model.fk_cliente_factura", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_pago_factura", "Pagos")]
        public Pagos Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pagos>("Database1Model.fk_pago_factura", "Pagos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pagos>("Database1Model.fk_pago_factura", "Pagos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pagos> PagosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pagos>("Database1Model.fk_pago_factura", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pagos>("Database1Model.fk_pago_factura", "Pagos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Pagos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pagos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pagos object.
        /// </summary>
        /// <param name="idPago">Initial value of the idPago property.</param>
        public static Pagos CreatePagos(global::System.Int64 idPago)
        {
            Pagos pagos = new Pagos();
            pagos.idPago = idPago;
            return pagos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha;
        partial void OnfechaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idPago
        {
            get
            {
                return _idPago;
            }
            set
            {
                if (_idPago != value)
                {
                    OnidPagoChanging(value);
                    ReportPropertyChanging("idPago");
                    _idPago = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPago");
                    OnidPagoChanged();
                }
            }
        }
        private global::System.Int64 _idPago;
        partial void OnidPagoChanging(global::System.Int64 value);
        partial void OnidPagoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fk_cliente
        {
            get
            {
                return _fk_cliente;
            }
            set
            {
                Onfk_clienteChanging(value);
                ReportPropertyChanging("fk_cliente");
                _fk_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_cliente");
                Onfk_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _fk_cliente;
        partial void Onfk_clienteChanging(Nullable<global::System.Int32> value);
        partial void Onfk_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fk_tipoCuota
        {
            get
            {
                return _fk_tipoCuota;
            }
            set
            {
                Onfk_tipoCuotaChanging(value);
                ReportPropertyChanging("fk_tipoCuota");
                _fk_tipoCuota = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_tipoCuota");
                Onfk_tipoCuotaChanged();
            }
        }
        private Nullable<global::System.Int32> _fk_tipoCuota;
        partial void Onfk_tipoCuotaChanging(Nullable<global::System.Int32> value);
        partial void Onfk_tipoCuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_vencimiento
        {
            get
            {
                return _fecha_vencimiento;
            }
            set
            {
                Onfecha_vencimientoChanging(value);
                ReportPropertyChanging("fecha_vencimiento");
                _fecha_vencimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_vencimiento");
                Onfecha_vencimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_vencimiento;
        partial void Onfecha_vencimientoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_vencimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ya_facturado
        {
            get
            {
                return _ya_facturado;
            }
            set
            {
                Onya_facturadoChanging(value);
                ReportPropertyChanging("ya_facturado");
                _ya_facturado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ya_facturado");
                Onya_facturadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _ya_facturado;
        partial void Onya_facturadoChanging(Nullable<global::System.Boolean> value);
        partial void Onya_facturadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_cliente_pago", "clientes")]
        public clientes clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.FK_cliente_pago", "clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.FK_cliente_pago", "clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<clientes> clientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<clientes>("Database1Model.FK_cliente_pago", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<clientes>("Database1Model.FK_cliente_pago", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_tipoCuota_pago", "Cuotas")]
        public Cuotas Cuotas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuotas>("Database1Model.fk_tipoCuota_pago", "Cuotas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuotas>("Database1Model.fk_tipoCuota_pago", "Cuotas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cuotas> CuotasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuotas>("Database1Model.fk_tipoCuota_pago", "Cuotas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cuotas>("Database1Model.fk_tipoCuota_pago", "Cuotas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "fk_pago_factura", "Facturas")]
        public EntityCollection<Facturas> Facturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Facturas>("Database1Model.fk_pago_factura", "Facturas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Facturas>("Database1Model.fk_pago_factura", "Facturas", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
